spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3307/mybatis-test?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
  application:
    name: redis-tool
  redis:
    host: 172.19.80.1
    port: 6370
    password: ""
logging:
  level:
    root: info
    web: debug
  config: classpath:logback-lyp.xml
server:
  port: 9999
mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
    default-enum-type-handler: com.l1yp.types.EnumCodeHandlers
#  type-handlers-package: com.l1yp.types